declare var path: any;
declare var config: any;
declare var uniqueArr: (list: any) => any;
declare var resolvePath: (str: any) => any;
declare var prePlugins: any;
declare var addon: any;
declare function addDebugPaths(plugins: any): void;
declare var pluginPaths: any;
declare var env: NodeJS.ProcessEnv;
declare var execPath: string;
declare var isWin: boolean;
declare var paths: any;
declare var globalDir: any;
declare var appDataDir: any;
declare var pluginsPath: any;
declare var nvmBin: string | undefined;
declare function addPluginPath(dir: any): void;
declare function formatPath(dir: any, prefix: any): any;
declare function getGlobalDir(): any;
