declare var net: any;
declare var http: any;
declare var extend: any;
declare var LRU: any;
declare var parseUrl: any;
declare var getServer: any;
declare var formatHeaders: any;
declare var common: any;
declare var socketProto: any;
declare var originConnect: any;
declare var SPEC_HOST_RE: RegExp;
declare var lru: any;
declare var PROXY_ID_HEADER: any;
declare var proxyIp: any;
declare var proxyPort: any;
declare function normalizeArgs(args: any): any[];
declare function createSocket(opts: any, cb: any): void;
