export function getUpdateUrl(conf: any): any;
export function noop(): void;
export function lowerCaseify(obj: any, rawNames: any): {};
export function removeIllegalTrailers(headers: any): void;
export function addTrailerNames(res: any, newTrailers: any, rawNames: any, delTrailers: any, req: any): void;
export function onResEnd(res: any, callback: any): any;
export function writeLogSync(msg: any): void;
export var REMOTE_URL_RE: RegExp;
export function isHead(req: any): boolean;
export function removeIPV6Prefix(ip: any): string;
export function hasBody(res: any, req: any): boolean;
export function isEmptyObject(a: any): boolean;
export function isWebSocket(options: any, headers: any): any;
export function isConnect(options: any): boolean;
export function hasProtocol(url: any): boolean;
export function setProtocol(url: any, isHttps: any): any;
export function getProtocol(url: any): any;
export function removeProtocol(url: any, clear: any): any;
export function replaceProtocol(url: any, protocol: any): any;
export function getHomedir(): string;
export function getHomePath(dir: any): any;
export function getWhistlePath(): any;
export function getLogFile(name: any): string;
