declare const _exports: {
    memUsage: NodeJS.MemoryUsage;
    uptime: number;
    cpuPercent: string;
    startupTime: number;
    updateTime: number;
    httpRequests: number;
    allHttpRequests: number;
    wsRequests: number;
    allWsRequests: number;
    tunnelRequests: number;
    totalHttpRequests: number;
    totalWsRequests: number;
    totalTunnelRequests: number;
    totalAllHttpRequests: number;
    totalAllWsRequests: number;
    httpQps: number;
    tunnelQps: number;
    wsQps: number;
    totalQps: number;
    maxQps: number;
    maxAllQps: number;
    maxRss: number;
    maxCpu: number;
    maxQpsTime: number;
    maxAllQpsTime: number;
    maxRssTime: number;
    maxCpuTime: number;
};
export = _exports;
