declare var path: any;
declare var http: any;
declare var fs: any;
declare var net: any;
declare var dns: any;
declare var https: any;
declare var crypto: Crypto;
declare var qs: any;
declare var LRU: any;
declare var httpAgent: any;
declare var httpsAgent: any;
declare var url: any;
declare var fse: any;
declare var Buffer: any;
declare var extend: any;
declare var tunnel: any;
declare var socks: any;
declare var json5: any;
declare var pkgConf: any;
declare var config: any;
declare var common: any;
declare var customUIHost: any;
declare var customHostPluginMap: {};
declare var customPluginNameHost: {};
declare var WHISTLE_PLUGIN_RE: RegExp;
declare var CMD_RE: RegExp;
declare var httpsAgents: any;
declare var socksAgents: any;
declare var version: string[];
declare var disableAgent: boolean;
declare var uid: string;
declare var IPV4_RE: RegExp;
declare var IPV6_RE: RegExp;
declare var noop: () => void;
declare var DATA_KEY_RE: RegExp;
declare var LOCAL_UI_HOST_LIST: string[];
declare var variableProperties: string[];
declare var KEEP_ALIVE_MSECS: number;
declare var CONN_TIMEOUT: number;
declare var getHomedir: any;
declare var getHomePath: any;
declare var getWhistlePath: any;
declare function getDataDir(dirname: any): any;
declare var async_id_symbol: any;
declare var emptyHandle: {
    asyncReset: () => void;
    getAsyncId: () => void;
};
declare function createAgent(agentConfig: any, https: any): any;
declare function capitalize(str: any): any;
declare function getHttpsAgent(options: any, reqOpts: any): any;
declare function getCacheKey(options: any, isSocks: any): string;
declare function getAuths(_url: any): any;
declare function getTunnelPath(headers: any): any;
declare function connect(options: any, cb: any): any;
declare function preventThrowOutError(socket: any): void;
declare function freeSocketErrorListener(this: any): void;
declare function resolvePath(file: any): any;
declare function getPaths(paths: any, isCustom: any): any;
declare function getSecureFilter(newConf: any): any;
declare function createHash(str: any): any;
declare function getHostPort(str: any): {
    host: string;
    port: number;
} | undefined;
declare function isPort(port: any): boolean;
declare function setGuestAuth(auth: any): void;
declare function parseString(str: any): any;
declare function getPluginList(list: any): any;
