declare var express: any;
declare var http: any;
declare var https: any;
declare var socks: any;
declare var extend: any;
declare var EventEmitter: any;
declare var util: any;
declare var logger: any;
declare var rules: any;
declare var setupHttps: any;
declare var httpsUtil: any;
declare var rulesUtil: any;
declare var initDataServer: any;
declare var initLogServer: any;
declare var pluginMgr: any;
declare var config: any;
declare var loadService: any;
declare var initSocketMgr: any;
declare var tunnelProxy: any;
declare var upgradeProxy: any;
declare var proc: any;
declare var perf: any;
declare var loadCert: any;
declare var common: any;
declare function handleClientError(err: any, socket: any): any;
declare function proxy(callback: any, _server: any): any;
declare function exportInterfaces(obj: any): any;
declare function handleGlobalException(err: any): void;
