declare var net: any;
declare var tls: any;
declare var extend: any;
declare var path: any;
declare var cluster: any;
declare var os: any;
declare var assert: any;
declare var common: any;
declare var ver: string[];
declare var PROD_RE: RegExp;
declare var noop: () => void;
declare var state: {};
declare var INTERVAL: number;
declare var TIMEOUT: number;
declare var MASTER_TIMEOUT: number;
declare var env: NodeJS.ProcessEnv;
declare function loadConfig(options: any): any;
declare function likePromise(p: any): any;
declare function killWorker(worker: any): void;
declare function forkWorker(index: any): void;
