declare var EventEmitter: any;
declare var zlib: any;
declare var util: any;
declare var socketMgr: any;
declare var config: any;
declare var MAX_BODY_SIZE: number;
declare var MAX_SIZE: number;
declare var MAX_REQ_BODY_SIZE: number;
declare var MAX_RES_BODY_SIZE: number;
declare var BIG_DATA_SIZE: number;
declare var LOCALHOST: string;
declare function getZipType(options: any): any;
declare function unzipBody(options: any, body: any, callback: any): any;
declare function getChunkLen(chunk: any): any;
declare function checkType(res: any): any;
declare function checkBodySize(data: any, useBigData: any): void;
declare function isUnzipJs(r: any): boolean;
declare function getEventName(proxy: any): "_request" | "httpRequest" | undefined;
declare function emitDataEvents(req: any, res: any, proxy: any): void;
