declare var https: any;
declare var http: any;
declare var net: any;
declare var url: any;
declare var mime: any;
declare var extend: any;
declare var util: any;
declare var Transform: any;
declare var h2: any;
declare var rules: any;
declare var pluginMgr: any;
declare var hparser: any;
declare var config: any;
declare var WhistleTransform: any;
declare var SpeedTransform: any;
declare var ReplacePatternTransform: any;
declare var ReplaceStringTransform: any;
declare var FileWriterTransform: any;
declare var formatHeaders: any;
declare var getRawHeaderNames: any;
declare var TIMEOUT: number;
declare var LOCALHOST: string;
declare var DOCTYPE: any;
declare var CRLF: any;
declare var MAX_RES_SIZE: number;
declare var JSON_RE: RegExp;
declare var LIKE_JSON_RE: RegExp;
declare var X_RE: RegExp;
declare var BODY_PROTOCOLS: string[];
declare var BODY_PROTOCOLS_LEN: number;
declare function notAllowCache(resRules: any): true | undefined;
declare function pipeClient(req: any, client: any): void;
declare function showDnsError(res: any, err: any): void;
declare function setCookies(headers: any, data: any): void;
declare function getWriterFile(file: any, statusCode: any): any;
declare function readFirstChunk(req: any, res: any, src: any, cb: any): any;
declare function checkH2(req: any, isHttps: any): void;
